# Generated by Django 3.1.5 on 2021-01-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor', models.CharField(blank=True, max_length=6, null=True, verbose_name='姓名')),
                ('gender', models.BooleanField(blank=True, null=True, verbose_name='性别')),
                ('id_no', models.CharField(blank=True, max_length=18, null=True, verbose_name='身份证号')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='住址')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='联系电话')),
                ('temp', models.FloatField(verbose_name='体温')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='登记时间')),
                ('visitee', models.CharField(blank=True, max_length=6, null=True, verbose_name='探视患者')),
                ('bk1', models.CharField(blank=True, max_length=6, null=True, verbose_name='bk1')),
                ('bk2', models.CharField(blank=True, max_length=8, null=True, verbose_name='bk2')),
                ('bk3', models.CharField(blank=True, max_length=8, null=True, verbose_name='bk3')),
                ('valid', models.BooleanField(default=True, verbose_name='记录状态')),
            ],
        ),
    ]
