# Generated by Django 3.1.5 on 2021-08-12 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idReader', '0002_auto_20210811_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='bk1',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='bk1'),
        ),
    ]
